import = [
    "~/.config/alacritty/themes/gruvbox_material_hard_dark.toml"
]

live_config_reload = true

[shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
padding = { x = 2, y = 2 }
decorations = "None"
opacity = 0.8
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x32302f"
foreground = "0xd4be98"

[colors.normal]
black = "0x45403d"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.bright]
black = "0x45403d"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "A", mods = "Alt", chars = "\u001Ba" },
    { key = "B", mods = "Alt", chars = "\u001Bb" },
    { key = "C", mods = "Alt", chars = "\u001Bc" },
    { key = "D", mods = "Alt", chars = "\u001Bd" },
    { key = "E", mods = "Alt", chars = "\u001Be" },
    { key = "F", mods = "Alt", chars = "\u001Bf" },
    { key = "G", mods = "Alt", chars = "\u001Bg" },
    { key = "H", mods = "Alt", chars = "\u001Bh" },
    { key = "I", mods = "Alt", chars = "\u001Bi" },
    { key = "J", mods = "Alt", chars = "\u001Bj" },
    { key = "K", mods = "Alt", chars = "\u001Bk" },
    { key = "L", mods = "Alt", chars = "\u001Bl" },
    { key = "M", mods = "Alt", chars = "\u001Bm" },
    { key = "N", mods = "Alt", chars = "\u001Bn" },
    { key = "O", mods = "Alt", chars = "\u001Bo" },
    { key = "P", mods = "Alt", chars = "\u001Bp" },
    { key = "Q", mods = "Alt", chars = "\u001Bq" },
    { key = "R", mods = "Alt", chars = "\u001Br" },
    { key = "S", mods = "Alt", chars = "\u001Bs" },
    { key = "T", mods = "Alt", chars = "\u001Bt" },
    { key = "U", mods = "Alt", chars = "\u001Bu" },
    { key = "V", mods = "Alt", chars = "\u001Bv" },
    { key = "W", mods = "Alt", chars = "\u001Bw" },
    { key = "X", mods = "Alt", chars = "\u001Bx" },
    { key = "Y", mods = "Alt", chars = "\u001By" },
    { key = "Z", mods = "Alt", chars = "\u001Bz" },
    { key = "A", mods = "Alt|Shift", chars = "\u001BA" },
    { key = "B", mods = "Alt|Shift", chars = "\u001BB" },
    { key = "C", mods = "Alt|Shift", chars = "\u001BC" },
    { key = "D", mods = "Alt|Shift", chars = "\u001BD" },
    { key = "E", mods = "Alt|Shift", chars = "\u001BE" },
    { key = "F", mods = "Alt|Shift", chars = "\u001BF" },
    { key = "G", mods = "Alt|Shift", chars = "\u001BG" },
    { key = "H", mods = "Alt|Shift", chars = "\u001BH" },
    { key = "I", mods = "Alt|Shift", chars = "\u001BI" },
    { key = "J", mods = "Alt|Shift", chars = "\u001BJ" },
    { key = "K", mods = "Alt|Shift", chars = "\u001BK" },
    { key = "L", mods = "Alt|Shift", chars = "\u001BL" },
    { key = "M", mods = "Alt|Shift", chars = "\u001BM" },
    { key = "N", mods = "Alt|Shift", chars = "\u001BN" },
    { key = "O", mods = "Alt|Shift", chars = "\u001BO" },
    { key = "P", mods = "Alt|Shift", chars = "\u001BP" },
    { key = "Q", mods = "Alt|Shift", chars = "\u001BQ" },
    { key = "R", mods = "Alt|Shift", chars = "\u001BR" },
    { key = "S", mods = "Alt|Shift", chars = "\u001BS" },
    { key = "T", mods = "Alt|Shift", chars = "\u001BT" },
    { key = "U", mods = "Alt|Shift", chars = "\u001BU" },
    { key = "V", mods = "Alt|Shift", chars = "\u001BV" },
    { key = "W", mods = "Alt|Shift", chars = "\u001BW" },
    { key = "X", mods = "Alt|Shift", chars = "\u001BX" },
    { key = "Y", mods = "Alt|Shift", chars = "\u001BY" },
    { key = "Z", mods = "Alt|Shift", chars = "\u001BZ" },
    { key = "Key1", mods = "Alt", chars = "\u001B1" },
    { key = "Key2", mods = "Alt", chars = "\u001B2" },
    { key = "Key3", mods = "Alt", chars = "\u001B#" },
    { key = "Key4", mods = "Alt", chars = "\u001B4" },
    { key = "Key5", mods = "Alt", chars = "\u001B5" },
    { key = "Key6", mods = "Alt", chars = "ยง" },
    { key = "Key7", mods = "Alt", chars = "\u001B7" },
    { key = "Key8", mods = "Alt", chars = "\u001B8" },
    { key = "Key9", mods = "Alt", chars = "\u001B9" },
    { key = "Key0", mods = "Alt", chars = "\u001B0" },
    { key = "Space", mods = "Control", chars = "\u0000" },
    { key = "Comma", mods = "Alt", chars = "\u001B," },
    { key = "Period", mods = "Alt", chars = "\u001B." },
    { key = "Key8", mods = "Alt|Shift", chars = "\u001B*" },
    { key = "Key3", mods = "Alt|Shift", chars = "\u001B#" },
    { key = "Period", mods = "Alt|Shift", chars = "\u001B>" },
    { key = "Comma", mods = "Alt|Shift", chars = "\u001B<" },
    { key = "Minus", mods = "Alt|Shift", chars = "\u001B_" },
    { key = "Key5", mods = "Alt|Shift", chars = "\u001B%" },
    { key = "Key6", mods = "Alt|Shift", chars = "\u001B^" },
    { key = "Backslash", mods = "Alt", chars = "\u001B\\" },
    { key = "Backslash", mods = "Alt|Shift", chars = "\u001B|" },
    { key = "Left", mods = "Alt", chars = "\u001Bb" },
    { key = "Right", mods = "Alt", chars = "\u001Bf" },
    { key = "Left", mode = "AppCursor", mods = "Command", chars = "\u001BOH" },
    { key = "Right", mode = "AppCursor", mods = "Command", chars = "\u001BOF" },
    { key = "Back", mods = "Command", chars = "\u0015" },
    { key = "Back", mods = "Alt", chars = "\u001B\u007F" }
]
